language: c

before_install:
 # Make sure mono is installed,
 # pipe stdout to dev/null because qq is still too chatty
 - echo "deb http://http.us.debian.org/debian/ unstable main contrib non-free" | sudo tee -a /etc/apt/sources.list
 - echo "deb-src http://http.us.debian.org/debian/ unstable main contrib non-free " | sudo tee -a /etc/apt/sources.list
 - sudo apt-get update -qq > /dev/null
 - sudo apt-get install -qq --force-yes mono-devel > /dev/null
 - sudo apt-get install -qq --force-yes fsharp > /dev/null
 

env:
  - EnableNuGetPackageRestore=true

script:
  - xbuild 
  - .ci/nunit.sh Tests/bin/Debug/Tests.dll
