language: objective-c

before_install:
 # Make sure mono is installed,
 - wget http://download.mono-project.com/archive/3.0.10/macos-10-x86/MonoFramework-MDK-3.0.10.macos10.xamarin.x86.dmg
 - hdid MonoFramework-MDK-3.0.10.macos10.xamarin.x86.dmg
 - sudo installer -pkg "/Volumes/Mono Framework MDK 3.0.10/MonoFramework-MDK-3.0.10.macos10.xamarin.x86.pkg" -target /
env:
  - EnableNuGetPackageRestore=true

script:
  - xbuild 
  - .ci/nunit.sh Tests/bin/Debug/Tests.dll
